//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public information()
        {
            this.aditionalInformations = new HashSet<aditionalInformation>();
        }
    
        public int id { get; set; }
        public string usuario { get; set; }
        public string identificacion { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string contrasena { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aditionalInformation> aditionalInformations { get; set; }
    }
}
